[versions]
android-gradle-plugin = "8.2.2"
kotlin-gradle-plugin = "1.9.23"  # ✅ Upgrade to Kotlin 1.9.23
google-services = "4.3.15"
compose-compiler = "1.5.12"
media3-common-ktx = "1.5.1"
volley = "1.2.1"
[libraries]
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3-common-ktx" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }  # ✅ Ensure correct Compose Compiler version

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle-plugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
